version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fpdlswj365
      MYSQL_DATABASE: batchdb
      MYSQL_USER: sunjae
      MYSQL_PASSWORD: fpdlswj365
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
